// Generate the computer's move using Math.random()

const compMoves = ["Rock", "Paper", "Scissors"]

function computerPlay() {
    // returns an index based on a random number generated by Math.random(), added -1 to include index 0
    return compMoves[Math.floor(Math.random() * compMoves.length)];
}

let playerSelection = prompt("What's your move?").toLowerCase();
let computerSelection = computerPlay().toLowerCase();

console.log(playerSelection);
console.log(computerSelection);

function playRound(playerSelection, computerSelection) {
    if (playerSelection === computerSelection) {
        console.log("It's a draw!");
    } else if(playerSelection === 'rock' && computerSelection === 'paper'){
        console.log("You lose! Paper beats Rock.");
    } else if (playerSelection === 'rock' && computerSelection === 'scissors'){
        console.log("You win! Rock beats Scissors.");
    } else if (playerSelection === 'paper' && computerSelection === 'rock') {
        console.log("You win! Paper beats Rock.");
    } else if (playerSelection === 'paper' && computerSelection === 'scissors') {
        console.log("You lose! Scissors beats Paper.");
    } else if (playerSelection === 'scissors' && computerSelection === 'rock') {
        console.log("You lose! Rock beats Scissors.");
    } else if (playerSelection === 'scissors' && computerSelection === 'paper') {
        console.log("You win! Scissors beats Paper.");
    } else{
        console.log("Please insert a valid move to play (rock, paper or scissors).");
    }
}

console.log(playRound(playerSelection, computerSelection));